kubectl apply -f - <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-pattern-exporter-configs
  namespace: default
data:
  error-config.yaml: |
    loki:
      endpoint: "http://loki-read.monitoring.svc.cluster.local:3100"
      query: '{app="log-generator"} |= "Hello"'
      interval: "1m"
      pattern: "Hello"
      interval: "1m"
      region_emoji: ":flag_us:"
      region_text: "dev-3"
      alert_name: "MyCustomAlert"
    slack:
      token: "${SLACK_TOKEN}"
      channel: "${SLACK_CHANNEL}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-pattern-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-pattern-exporter
  template:
    metadata:
      labels:
        app: loki-pattern-exporter
    spec:
      containers:
      - name: loki-pattern-exporter
        image: ghcr.io/zmmdv/loki-pattern-log-exporter:sha-1e29b07
        ports:
        - containerPort: 8080
          name: health
        livenessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /app/configuration
        env:
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-secrets
              key: token
        - name: SLACK_CHANNEL
          valueFrom:
            secretKeyRef:
              name: slack-secrets
              key: channel
      volumes:
      - name: config-volume
        configMap:
          name: loki-pattern-exporter-configs
EOF