apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-pattern-exporter-configs
data:
  error-config.yaml: |
    loki:
      endpoint: "http://loki:3100"
      query: '{job="test-logs"}'
      pattern: "error|exception|critical"
      interval: "1m"
    slack:
      token: "${SLACK_TOKEN}"
      channel: "${SLACK_CHANNEL}"

  warning-config.yaml: |
    loki:
      endpoint: "http://loki:3100"
      query: '{job="test-logs"}'
      pattern: "warning|warn"
      interval: "5m"
    slack:
      token: "${SLACK_TOKEN}"
      channel: "${SLACK_CHANNEL}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-pattern-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-pattern-exporter
  template:
    metadata:
      labels:
        app: loki-pattern-exporter
    spec:
      containers:
      - name: loki-pattern-exporter
        image: loki-pattern-exporter:latest
        ports:
        - containerPort: 8080
          name: health
        livenessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /app/configuration
        env:
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-secrets
              key: token
        - name: SLACK_CHANNEL
          valueFrom:
            secretKeyRef:
              name: slack-secrets
              key: channel
      volumes:
      - name: config-volume
        configMap:
          name: loki-pattern-exporter-configs 