apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-pattern-exporter-config
  namespace: default
data:
  config.yaml: |
    loki:
      endpoint: "http://loki-read.monitoring.svc.cluster.local:3100"
      query: "{app="log-generator"} |= `Hello`"
      pattern: "error|exception|critical"
      interval: "1m"
    slack:
      token: "${SLACK_TOKEN}"
      channel: "${SLACK_CHANNEL}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-pattern-exporter
  labels:
    app: loki-pattern-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-pattern-exporter
  template:
    metadata:
      labels:
        app: loki-pattern-exporter
    spec:
      containers:
      - name: loki-pattern-exporter
        image: loki-pattern-exporter:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: LOKI_ENDPOINT
          value: "http://loki:3100"
        - name: LOKI_QUERY
          value: '{job="your-job-name"}'
        - name: LOKI_PATTERN
          value: "error|exception|critical"
        - name: LOKI_INTERVAL
          value: "1m"
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-secrets
              key: token
        - name: SLACK_CHANNEL
          valueFrom:
            secretKeyRef:
              name: slack-secrets
              key: channel
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: config-volume
        configMap:
          name: loki-pattern-exporter-config 