kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: log-generator
  namespace: default
  labels:
    app: log-generator
    job: test-logs
spec:
  containers:
  - name: log-generator
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo '$(date) - Hello World! This is a test log message.'; sleep 25; done"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
EOF